---
title: "GeneModuleAnnotation"
author: "Tao Fang"
date: "4/6/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## load necesseary package
```{r}
library(devtools)
library(roxygen2)
setwd("~/Documents/GeneModuleAnnotationPaper/code")
library(Matrix)
library(GENEMABR)
```
## create R pacakge
```{r}
#setwd("~/Documents/GeneModuleAnnotationPaper/code/")
#create("GENEMABR")

## including some data in the package
## following link in https://bookdown.org/rdpeng/RProgDA/data-within-a-package.html
## first save it as raw data so users can get access to it
##then transfer to internal data so package can use it easily 
human_go_ontology=readRDS(system.file("extdata", "go_ontology.rds", package = "GENEMABR"))
human_reactome_ontology=readRDS(system.file("extdata", "human_reactome_ontology.rds", package = "GENEMABR"))
gene_pathway_matrix=readRDS(system.file("extdata", "gene_pathway_matrix.rds", package = "GENEMABR"))
setwd("~/Documents/GeneModuleAnnotationPaper/code/GENEMABR")
#use_data(human_go_ontology,human_reactome_ontology,gene_pathway_matrix,internal = T,overwrite = T)
## then document data  in data.R files
## for now temporily remove data.R file until finally finishing pacakge 

# steps to procees documentation for the pacakge
setwd("~/Documents/GeneModuleAnnotationPaper/code/GENEMABR")
document()
setwd("~/Documents/GeneModuleAnnotationPaper/code")
install("GENEMABR")
library(GENEMABR)

```



## set data path
```{r}
raw_data_path="~/Documents/DreamChallengeModuleAnnotation/HPC_Disease_module_identification_DREAM_change/"
```


# Test function in R package

### test regression_selected_pathways
```{r}
gene_input=c("TRPC4AP","CDC37","TNIP1","IKBKB","NKIRAS2","NFKBIA","TIMM50","RELB","TNFAIP3","NFKBIB","HSPA1A","NFKBIE",
"SPAG9","NFKB2","ERLIN1","REL","TNIP2","TUBB6","MAP3K8")
```











